### ISSUE TITLE
checklist for merging card-reducer

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1488]
done:

- [x] fix #1471 - make all characters work and test all characters
- [x] fix #1489 - bottom-deck blind-plays
- [x] fix #1491 - shadow looks buggy when playing a card
- [x] fix #1493 - replay on the first turn of a game
- [x] fix #1506 - shadow draw bug
- [x] fix #1505 - make number pips look better
- [x] fix #1522 - card stuck in empathy
- [x] fix #1385 - throw it in a hole

todo:

- [x] fix #1518 - card tweening bug (rob)

**Comment by robertos** [comment]
I think I got 'em all :)

**Comment by Zamiell** [comment]
found more bugs BibleThump

**Comment by Zamiell** [comment]
horray
