### ISSUE TITLE
hypothetical todo

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1876]
TODO after merging:

- [x] prompt user for card identity when playing/discarding an unknown card
- [x] allow clues to self when cards are morphed and would be touched
- [ ] add back Show Drawn Cards button when hypo is started on a turn that does not equal the most present turn
- [x] automatically morph all cards in hand according to identity notes when starting hypothetical for ease of use.
- [x] align the hypo buttons during private out-of-game replay

**Comment by timotree3** [comment]
> align the hypo buttons during private out-of-game replay
The enter hypo button should be center aligned in this case, but right-aligned otherwise. Do I have to make two separate buttons and toggle each of their visibility?

**Comment by Zamiell** [comment]
no, copy the code that moves the "Use Shared Turns" button or whatever

**Comment by Zamiell** [comment]
because that button changes position depending on whether or not you are the replay leader or a replay follower

**Comment by Zamiell** [comment]
1/5 done

**Comment by Zamiell** [comment]
2/5

**Comment by timotree3** [comment]
items 2 and 4 seem to already work for free.

**Comment by Zamiell** [comment]
what a deal

**Comment by Zamiell** [comment]
should i close this now

**Comment by DrAnax** [comment]
@timotree3 @Zamiell should this be closed?

**Comment by Zamiell** [comment]
i guess
